
 log_format time_combined '$remote_addr - $remote_user [$time_local] '
                      '$request_id "$request" $status $body_bytes_sent '
                      '"$http_referer" "$http_user_agent" '
                      '$request_time $upstream_response_time $upstream_addr';

 client_max_body_size 25M;
 server {
   listen 80; 
   server_name _;
   port_in_redirect off;
   absolute_redirect off;   
   resolver 127.0.0.11 valid=30s;


    location /tejas {
        proxy_pass http://tejas:8028;  # Replace with the IP and port of your Spring server
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;
    }
}

