kafka.bootstrap-servers=kafka-bootstrap.star.syncfusion.in:443
kafka.bootstrap.security.protocol=SSL
kafka.bootstrap.trust.store.location=/tmp/truststore.jks
kafka.bootstrap.trust.store.password=****
kafka.group-id=group_id
management.context-path=/syncfusion

gmail.observer.email=****

redis.nodes=redis-19523.c264.ap-south-1-1.ec2.cloud.redislabs.com:19523
redis.password=****
redis.isClusterEnabled=false
redis.maxWaitMillis=10000
redis.maxTotalConnections=100
redis.isTestOnBorrow=true
redis.maxIdleConnections=10

server.port=8028
server.servlet.context-path=/syncfusion

spring.datasource.url=jdbc:mysql://34.100.149.90:3306/syncfusion?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
spring.datasource.username=****
spring.datasource.password=****
spring.jpa.hibernate.ddl-auto=update

hood.baseUrl=https://bb-mimo-erp.hood.blackbox.syncfusion.com/

brahmos.cloufunctions.createnewpost.url=https://us-central1-syncfusion-stage.cloudfunctions.net/createnewpost
brahmos.cloufunctions.createnewreply.url=https://us-central1-syncfusion-stage.cloudfunctions.net/addreplytopost
brahmos.cloufunctions.createnewnestedreply.url=https://us-central1-syncfusion-stage.cloudfunctions.net/addnestedreply
brahmos.cloufunctions.getforumreplies.url=https://us-central1-syncfusion-stage.cloudfunctions.net/getreplydata

brahmos.cloufunctions.authorization.token=****

syncfusion.gmail.history.process.replay.allowed=false

hood.deeplink.baseUrl=https://syncfusion.co/dec

gmail.service.impersonate.user.email=****

google.service.account.file.path=gmail/serviceAccountCredentials.json

syncfusion.notification.authkey=****
syncfusion.notification.crmUserId=****

admin.emails=****

syncfusion.notification.provider=SENDGRID

gcp.service.account.file.path=gcp/gcp_service_account.json
